name: Node.js CI

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3 

      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run dev
