name: Node.js CI

on:
- pull_request
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # fetch repo files
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Backend build (if you want to install but not run dev)
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      # # Frontend build
      # - name: Install frontend dependencies
      #   run: npm install
      #   working-directory: ./frontend
      # - name: Build frontend
      #   run: npm run build
      #   working-directory: ./frontend
      - name: Test Backend
        run: npm run dev &
        # to prevent blocking terminal , thats the reason for infinte test
        working-directory: ./backend
        env:
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          PORT: 3000
      - name: Waiting for server to start
        run : sleep 10
      - name : Checking if the Api started
        run : http://localhost:3000/pickkachu
       
